export {default as clonMinecraftImg} from './ClonMinecraft.JPG'
export {default as carritoComprasImg} from './Carrito de compras.JPG'
export {default as gestorImagenesImg} from './GDI.JPG'
export {default as gestorNominaPHPImg} from './GDNPHP.JPG'
export {default as gestorNominaReactImg} from './GDNREACT.JPG'
export {default as personajesRAMImg} from './PersonajesRickAndMorty.JPG'
